name: emerson
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  get_it: ^7.5.0
  intl: ^0.17.0
  rxdart: ^0.27.7
  talker_dio_logger: ^1.3.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  #duolingo_page
  - assets/images/appBar/crown_stroke.png
  - assets/images/appBar/flag.png
  - assets/images/appBar/navbar_diamont.png
  - assets/images/appBar/navbar_fire.png
  
  - assets/images/lesson_egg.png
  - assets/images/lesson_airplane.png
  - assets/images/store_item_8.png
  - assets/images/lesson_hamburger.png
  - assets/images/lesson_baby.png
  - assets/images/lesson_dialog.png
  - assets/images/lesson_divisor_castle.png
  
  #Ahorcado
  - assets/anged/0.png
  - assets/anged/1.png
  - assets/anged/2.png
  - assets/anged/3.png
  - assets/anged/4.png
  